from ParserAll import *
from BuyAll import *
from ItemOperations import *

print('Choose bot type: 1 - Royal City Scan Bot; 2 - Black Market Scan Bot; 3 - Order-Buy Bot; 4 - Fust-Buy Bot; 5 - Order-Sell Bot')
print('Input option and press ENTER: ')
bottype = input()

if bottype == '1':
    print('You chose Royal City Scan Bot')
    print('Choose city for scan: 1 - Thetford; 2 - Fort Sterling; 3 - Lymhurst; 4 - Bridgewatch; 5 - Martlock')
    print('Input option and press ENTER: ')
    city = input()
    print('Choose tier(s) for scan: 4 - T4, 5 - T5, 6 - T6, 7 - T7, 8 - T8')
    print('Input option(s) and press ENTER: ')
    tier = input()
    print('Choose enchantement(s) for scan: 0 - .0; 1 - .1; 2 - .2')
    print('Input option(s) and press ENTER: ')
    enchantement = input()
    print('Choose what buy method use for scan: 1 - Fast Buy, 2 - Order Buy')
    print('Input option(s) and press ENTER: ')
    payment = input()
    print('Options: ')
    print('City: ',city,'Tier(s): ',tier, 'Enchantment(s): ', enchantement, 'Payment: ', payment)
    royalScan(tier, enchantement, city, payment)
if bottype == '2':
    print('You chose Black Market Scan Bot')
    print('Choose tier(s) for scan: 4 - T4, 5 - T5, 6 - T6, 7 - T7, 8 - T8')
    print('Input option(s) and press ENTER: ')
    tier = input()
    print('Choose enchantement(s) for scan: 0 - .0; 1 - .1; 2 - .2')
    print('Input option(s) and press ENTER: ')
    enchantement = input()
    print('Choose items part for scan: 1 - first group of t4+ items; 2 - second group of t4+ items; 3 - group fo t3+ items; 4 - group fo t2+ items; 5 - group fo t1+ items;')
    print('Input option(s) and press ENTER: ')
    part = input()
    blackMarketScan(tier, enchantement, part)
if bottype == '3':
    print('You chose Order-Buy Bot')
    print('Choose city for scan: 1 - Thetford; 2 - Fort Sterling; 3 - Lymhurst; 4 - Bridgewatch; 5 - Martlock')
    print('Input option and press ENTER: ')
    city = input()
    print('Choose tier(s) for scan: 4 - T4, 5 - T5, 6 - T6, 7 - T7, 8 - T8')
    print('Input option(s) and press ENTER: ')
    tier = input()
    print('Choose enchantement(s) for scan: 0 - .0; 1 - .1; 2 - .2')
    print('Input option(s) and press ENTER: ')
    enchantement = input()
    print('Enter interested profit for items search')
    print('Input option and press ENTER: ')
    profit = input()
    print('Enter budget for orders')
    print('Input option and press ENTER: ')
    budget = input()
    orderBuy(tier, enchantement, city, profit, budget)
if bottype == '4':
    print('You chose Fast-Buy Bot')
    print('Choose city for scan: 1 - Thetford; 2 - Fort Sterling; 3 - Lymhurst; 4 - Bridgewatch; 5 - Martlock')
    print('Input option and press ENTER: ')
    city = input()
    print('Choose tier(s) for scan: 4 - T4, 5 - T5, 6 - T6, 7 - T7, 8 - T8')
    print('Input option(s) and press ENTER: ')
    tier = input()
    print('Choose enchantement(s) for scan: 0 - .0; 1 - .1; 2 - .2')
    print('Input option(s) and press ENTER: ')
    enchantement = input()
    print('Enter interested profit for items search')
    print('Input option and press ENTER: ')
    profit = input()
    print('Enter budget for orders')
    print('Input option and press ENTER: ')
    budget = input()
    fastBuy(tier, enchantement, city, profit, budget)
if bottype == '5':
    print('You chose Order-Sell Bot')
    #print('Enter City: 1 - Royal, 2 - BlackMarket')
    #city = input()
    orderSellOperations()
